/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pagos.app;

import pagos.cuentas.*;
import pagos.metodos.*;
import pagos.excepciones.*;

/**
 *
 * @author delcenjo
 */
public class AppGUI extends javax.swing.JFrame {

    private CuentaBancaria banco;
    private CuentaBizum bizum1;
    private CuentaPayPal paypal;

    public AppGUI() {
        initComponents();

        try {
            banco = new CuentaBancaria("C001", "Juan Pérez", 5000, "ES7921000813610123456789");
            bizum1 = new CuentaBizum("B001", "Ana Gómez", 800, "612345678");
            paypal = new CuentaPayPal("P001", "Marta Díaz", 1200, "marta@email.com");
        } catch (CantidadIncorrectaException | IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error creando cuentas: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        comboMetodo.removeAllItems();
        comboMetodo.addItem("Bizum");
        comboMetodo.addItem("PayPal");
        comboMetodo.addItem("Tarjeta");
        comboMetodo.setSelectedIndex(-1);

        comboCuenta.removeAllItems();
        comboCuenta.addItem(banco);
        comboCuenta.addItem(bizum1);
        comboCuenta.addItem(paypal);
        comboCuenta.setSelectedIndex(-1);

        javax.swing.JOptionPane.showMessageDialog(this, String.format("Cuentas creadas correctamente:\nBanco: %.2f€\nBizum: %.2f€\nPayPal: %.2f€", banco.getSaldo(), bizum1.getSaldo(), paypal.getSaldo()), "Cuentas Iniciales", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblMetodo = new javax.swing.JLabel();
        comboMetodo = new javax.swing.JComboBox<>();
        lblCuenta = new javax.swing.JLabel();
        comboCuenta = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        panelSuperior.setBackground(new java.awt.Color(85, 155, 201));
        panelSuperior.setForeground(new java.awt.Color(33, 150, 243));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SISTEMA DE PAGOS");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelInferior.setBackground(new java.awt.Color(224, 224, 224));
        panelInferior.setForeground(new java.awt.Color(224, 224, 224));

        btnPagar.setBackground(new java.awt.Color(76, 175, 80));
        btnPagar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");
        btnPagar.setMaximumSize(new java.awt.Dimension(120, 40));
        btnPagar.setMinimumSize(new java.awt.Dimension(120, 40));
        btnPagar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnPagar.addActionListener(this::btnPagarActionPerformed);
        panelInferior.add(btnPagar);

        btnSalir.setBackground(new java.awt.Color(244, 67, 54));
        btnSalir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(120, 40));
        btnSalir.setMinimumSize(new java.awt.Dimension(120, 40));
        btnSalir.setPreferredSize(new java.awt.Dimension(120, 40));
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        panelInferior.add(btnSalir);

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelCentral.setBackground(new java.awt.Color(245, 245, 245));
        panelCentral.setForeground(new java.awt.Color(245, 245, 245));
        panelCentral.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        lblCantidad.setText("Cantidad (€):");
        panelCentral.add(lblCantidad);
        panelCentral.add(txtCantidad);

        lblMetodo.setText("Método:");
        panelCentral.add(lblMetodo);

        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bizum", "PayPal", "Tarjeta" }));
        panelCentral.add(comboMetodo);

        lblCuenta.setText("Cuenta:");
        panelCentral.add(lblCuenta);

        panelCentral.add(comboCuenta);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            String cantidadStr = txtCantidad.getText().trim();
            if (cantidadStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe introducir una cantidad");
                return;
            }
            double cantidad = Double.parseDouble(cantidadStr);
            if (cantidad != Math.floor(cantidad * 100) / 100) {
                javax.swing.JOptionPane.showMessageDialog(this, "Solo se permiten dos decimales en la cantidad");
                return;
            }
            String metodo = (String) comboMetodo.getSelectedItem();
            Object seleccionCuenta = comboCuenta.getSelectedItem();
            if (metodo == null || seleccionCuenta == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un método de pago y una cuenta");
                return;
            }
            Cuenta cuenta = (Cuenta) seleccionCuenta;
            String comprobante = "";
            switch (metodo) {
                case "Bizum":
                    if (!(cuenta instanceof CuentaBizum)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La cuenta seleccionada no es compatible con Bizum");
                        return;
                    }
                    PagoBizum pagoBizum = new PagoBizum(((CuentaBizum) cuenta).getTelefono());
                    pagoBizum.pagar(cantidad, cuenta);
                    comprobante = pagoBizum.obtenerComprobante();
                    break;
                case "PayPal":
                    if (!(cuenta instanceof CuentaPayPal)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La cuenta seleccionada no es compatible con PayPal");
                        return;
                    }
                    PagoPayPal pagoPayPal = new PagoPayPal(((CuentaPayPal) cuenta).getEmail());
                    pagoPayPal.pagar(cantidad, cuenta);
                    comprobante = pagoPayPal.obtenerComprobante();
                    break;
                case "Tarjeta":
                    if (!(cuenta instanceof CuentaBancaria)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Para pagar con tarjeta debe seleccionar la cuenta bancaria asociada");
                        return;
                    }
                    PagoTarjeta pagoTarjeta = new PagoTarjeta("1234567812345678", "Usuario Demo", (CuentaBancaria) cuenta);
                    pagoTarjeta.pagar(cantidad, (CuentaBancaria) cuenta);
                    comprobante = pagoTarjeta.obtenerComprobante();
                    break;
                default:
                    javax.swing.JOptionPane.showMessageDialog(this, "Método de pago no soportado");
                    return;
            }

            String mensajeFinal = comprobante + "\n"
                    + "Saldos actualizados:\n"
                    + "Banco: " + banco.getSaldo() + " €\n"
                    + "Bizum: " + bizum1.getSaldo() + " €\n"
                    + "PayPal: " + paypal.getSaldo() + " €";

            javax.swing.JOptionPane.showMessageDialog(this, mensajeFinal, "Pago Realizado", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            txtCantidad.setText("");
            comboMetodo.setSelectedIndex(-1);
            comboCuenta.setSelectedIndex(-1);

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cantidad inválida");
        } catch (SaldoInsuficienteException | CantidadIncorrectaException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error en el pago: " + ex.getMessage());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new AppGUI().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Cuenta> comboCuenta;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
