/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.delcenjo;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Interfaz gráfica del programa.
 * Responsable únicamente de la vista y delegación de eventos al gestor.
 *
 * @author José Miguel del Río Centeno
 */
public class CopiadorArchivos extends javax.swing.JFrame {

    private File archivoSeleccionado;
    private File carpetaDestino;
    private GestorArchivos gestorArchivos; // Referencia a la clase de lógica

    /**
     * Creates new form CopiadorArchivos
     */
    public CopiadorArchivos() {
        initComponents();
        setLocationRelativeTo(null);
        // Instanciamos la clase que se encargará de toda la lógica "sucia"
        gestorArchivos = new GestorArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtArchivoOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCarpetaDestino = new javax.swing.JTextField();
        btnSeleccionarArchivo = new javax.swing.JButton();
        btnSeleccionarDestino = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copiador de Archivos Multimedia - José Miguel del Río Centeno");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createEtchedBorder(),
                "Copia de archivos multimedia",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copiador de Archivos Multimedia");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Archivo origen:");

        txtArchivoOrigen.setEditable(false);
        txtArchivoOrigen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArchivoOrigen.setToolTipText("Ruta del archivo seleccionado");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Carpeta destino:");

        txtCarpetaDestino.setEditable(false);
        txtCarpetaDestino.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCarpetaDestino.setToolTipText("Ruta de la carpeta destino");

        btnSeleccionarArchivo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSeleccionarArchivo.setText("Seleccionar archivo...");
        btnSeleccionarArchivo.setToolTipText("Seleccionar imagen, audio o vídeo");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        btnSeleccionarDestino.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSeleccionarDestino.setText("Seleccionar destino...");
        btnSeleccionarDestino.setToolTipText("Seleccionar carpeta de destino");
        btnSeleccionarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarDestinoActionPerformed(evt);
            }
        });

        btnCopiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCopiar.setText("Copiar archivo");
        btnCopiar.setToolTipText("Realizar la copia del archivo");
        btnCopiar.setEnabled(false);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Cerrar la aplicación");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Formatos: Imágenes (jpg, png, gif, bmp) | Audio (mp3, wav, flac, ogg) | Vídeo (mp4, avi, mkv, mov)");

        jProgressBar1.setStringPainted(true);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 102, 153));
        lblEstado.setText("Estado: Esperando selección de archivo...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArchivoOrigen)
                            .addComponent(txtCarpetaDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeleccionarDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArchivoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarDestino))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnCopiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo multimedia");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter filtroImagenes = new FileNameExtensionFilter(
                "Imágenes (jpg, png, gif, bmp)", "jpg", "jpeg", "png", "gif", "bmp");
        FileNameExtensionFilter filtroAudio = new FileNameExtensionFilter(
                "Audio (mp3, wav, flac, ogg)", "mp3", "wav", "flac", "ogg");
        FileNameExtensionFilter filtroVideo = new FileNameExtensionFilter(
                "Vídeo (mp4, avi, mkv, mov)", "mp4", "avi", "mkv", "mov");
        FileNameExtensionFilter filtroTodos = new FileNameExtensionFilter(
                "Todos los archivos multimedia",
                "jpg", "jpeg", "png", "gif", "bmp",
                "mp3", "wav", "flac", "ogg",
                "mp4", "avi", "mkv", "mov");

        fileChooser.addChoosableFileFilter(filtroTodos);
        fileChooser.addChoosableFileFilter(filtroImagenes);
        fileChooser.addChoosableFileFilter(filtroAudio);
        fileChooser.addChoosableFileFilter(filtroVideo);
        fileChooser.setFileFilter(filtroTodos);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            txtArchivoOrigen.setText(archivoSeleccionado.getAbsolutePath());
            lblEstado.setText("Estado: Archivo seleccionado → " + archivoSeleccionado.getName());
            verificarHabilitarCopiar();
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnSeleccionarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarDestinoActionPerformed
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setDialogTitle("Seleccionar carpeta de destino");
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setAcceptAllFileFilterUsed(false);

        int resultado = folderChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            carpetaDestino = folderChooser.getSelectedFile();
            txtCarpetaDestino.setText(carpetaDestino.getAbsolutePath());
            lblEstado.setText("Estado: Carpeta destino seleccionada → " + carpetaDestino.getName());
            verificarHabilitarCopiar();
        }
    }//GEN-LAST:event_btnSeleccionarDestinoActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        if (archivoSeleccionado == null || !archivoSeleccionado.exists()) {
            JOptionPane.showMessageDialog(this,
                    "El archivo seleccionado no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (carpetaDestino == null || !carpetaDestino.isDirectory()) {
            JOptionPane.showMessageDialog(this,
                    "La carpeta de destino no es válida.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Delegamos al Gestor la tarea de crear el nuevo objeto File destino
        File archivoCopia = gestorArchivos.generarArchivoDestino(archivoSeleccionado, carpetaDestino);

        if (archivoCopia.exists()) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "Ya existe un archivo con el nombre \"" + archivoCopia.getName() + "\" en la carpeta destino.\n"
                    + "¿Desea sobrescribirlo?",
                    "Archivo existente",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
        }

        try {
            jProgressBar1.setValue(0);
            lblEstado.setText("Estado: Copiando archivo...");

            // Llamamos a la lógica enviándole un Listener (clase anónima) para que actualice la GUI
            gestorArchivos.copiarArchivo(archivoSeleccionado, archivoCopia, new ProgresoListener() {
                @Override
                public void actualizarProgreso(int porcentaje) {
                    jProgressBar1.setValue(porcentaje);
                }
            });

            jProgressBar1.setValue(100);
            lblEstado.setText("Estado: ¡Copia completada con éxito!");

            JOptionPane.showMessageDialog(this,
                    "Archivo copiado correctamente.\n\n"
                    + "Origen: " + archivoSeleccionado.getAbsolutePath() + "\n"
                    + "Destino: " + archivoCopia.getAbsolutePath(),
                    "Copia completada",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            jProgressBar1.setValue(0);
            lblEstado.setText("Estado: Error durante la copia.");
            JOptionPane.showMessageDialog(this,
                    "Error al copiar el archivo:\n" + ex.getMessage(),
                    "Error de copia",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Verifica si se han seleccionado archivo y carpeta destino
     * para habilitar el botón de copiar.
     */
    private void verificarHabilitarCopiar() {
        btnCopiar.setEnabled(archivoSeleccionado != null && carpetaDestino != null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnSeleccionarDestino;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtArchivoOrigen;
    private javax.swing.JTextField txtCarpetaDestino;
    // End of variables declaration//GEN-END:variables
}
