/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.delcenjo;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Interfaz gráfica del programa.
 * Responsable únicamente de la vista y delegación de eventos al gestor.
 *
 * @author José Miguel del Río Centeno
 */
public class CopiadorArchivos extends javax.swing.JFrame {

    private File archivoSeleccionado;
    private File carpetaDestino;
    private GestorArchivos gestorArchivos; // Referencia a la clase de lógica

    /**
     * Creates new form CopiadorArchivos
     */
    public CopiadorArchivos() {
        initComponents();
        setSize(610, 340); // Establecer tamaño fijo para la ventana
        setLocationRelativeTo(null);
        // Instanciamos la clase que se encargará de toda la lógica
        gestorArchivos = new GestorArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtArchivoOrigen = new javax.swing.JTextField();
        btnSeleccionarArchivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCarpetaDestino = new javax.swing.JTextField();
        btnSeleccionarDestino = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblEstado = new javax.swing.JLabel();
        btnCopiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copiador de Archivos Multimedia - José Miguel del Río Centeno");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copiador de Archivos Multimedia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Formatos: Imágenes | Audio | Vídeo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 560, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Archivo origen:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));

        txtArchivoOrigen.setEditable(false);
        getContentPane().add(txtArchivoOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, 30));

        btnSeleccionarArchivo.setText("Seleccionar...");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Carpeta destino:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        txtCarpetaDestino.setEditable(false);
        getContentPane().add(txtCarpetaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, 30));

        btnSeleccionarDestino.setText("Seleccionar...");
        btnSeleccionarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 30));

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 560, 25));

        lblEstado.setForeground(new java.awt.Color(0, 102, 153));
        lblEstado.setText("Estado: Esperando selección...");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 560, 20));

        btnCopiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCopiar.setText("Copiar");
        btnCopiar.setEnabled(false);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 120, 40));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo multimedia");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter filtroImagenes = new FileNameExtensionFilter(
                "Imágenes (jpg, png, gif, bmp)", "jpg", "jpeg", "png", "gif", "bmp");
        FileNameExtensionFilter filtroAudio = new FileNameExtensionFilter(
                "Audio (mp3, wav, flac, ogg)", "mp3", "wav", "flac", "ogg");
        FileNameExtensionFilter filtroVideo = new FileNameExtensionFilter(
                "Vídeo (mp4, avi, mkv, mov)", "mp4", "avi", "mkv", "mov");
        FileNameExtensionFilter filtroTodos = new FileNameExtensionFilter(
                "Todos los archivos multimedia",
                "jpg", "jpeg", "png", "gif", "bmp",
                "mp3", "wav", "flac", "ogg",
                "mp4", "avi", "mkv", "mov");

        fileChooser.addChoosableFileFilter(filtroTodos);
        fileChooser.addChoosableFileFilter(filtroImagenes);
        fileChooser.addChoosableFileFilter(filtroAudio);
        fileChooser.addChoosableFileFilter(filtroVideo);
        fileChooser.setFileFilter(filtroTodos);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            txtArchivoOrigen.setText(archivoSeleccionado.getAbsolutePath());
            lblEstado.setText("Estado: Archivo seleccionado → " + archivoSeleccionado.getName());
            verificarHabilitarCopiar();
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnSeleccionarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarDestinoActionPerformed
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setDialogTitle("Seleccionar carpeta de destino");
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setAcceptAllFileFilterUsed(false);

        int resultado = folderChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            carpetaDestino = folderChooser.getSelectedFile();
            txtCarpetaDestino.setText(carpetaDestino.getAbsolutePath());
            lblEstado.setText("Estado: Carpeta destino seleccionada → " + carpetaDestino.getName());
            verificarHabilitarCopiar();
        }
    }//GEN-LAST:event_btnSeleccionarDestinoActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        if (archivoSeleccionado == null || !archivoSeleccionado.exists()) {
            JOptionPane.showMessageDialog(this,
                    "El archivo seleccionado no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (carpetaDestino == null || !carpetaDestino.isDirectory()) {
            JOptionPane.showMessageDialog(this,
                    "La carpeta de destino no es válida.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Delegamos al Gestor la tarea de crear el nuevo objeto File destino
        File archivoCopia = gestorArchivos.generarArchivoDestino(archivoSeleccionado, carpetaDestino);

        if (archivoCopia.exists()) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "Ya existe un archivo con el nombre \"" + archivoCopia.getName() + "\" en la carpeta destino.\n"
                    + "¿Desea sobrescribirlo?",
                    "Archivo existente",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
        }

        try {
            jProgressBar1.setValue(0);
            lblEstado.setText("Estado: Copiando archivo...");

            // Llamamos a la lógica enviándole un Listener (clase anónima) para que actualice la GUI
            gestorArchivos.copiarArchivo(archivoSeleccionado, archivoCopia, new ProgresoListener() {
                @Override
                public void actualizarProgreso(int porcentaje) {
                    jProgressBar1.setValue(porcentaje);
                }
            });

            jProgressBar1.setValue(100);
            lblEstado.setText("Estado: ¡Copia completada con éxito!");

            JOptionPane.showMessageDialog(this,
                    "Archivo copiado correctamente.\n\n"
                    + "Origen: " + archivoSeleccionado.getAbsolutePath() + "\n"
                    + "Destino: " + archivoCopia.getAbsolutePath(),
                    "Copia completada",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            jProgressBar1.setValue(0);
            lblEstado.setText("Estado: Error durante la copia.");
            JOptionPane.showMessageDialog(this,
                    "Error al copiar el archivo:\n" + ex.getMessage(),
                    "Error de copia",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Verifica si se han seleccionado archivo y carpeta destino
     * para habilitar el botón de copiar.
     */
    private void verificarHabilitarCopiar() {
        btnCopiar.setEnabled(archivoSeleccionado != null && carpetaDestino != null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnSeleccionarDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtArchivoOrigen;
    private javax.swing.JTextField txtCarpetaDestino;
    // End of variables declaration//GEN-END:variables
}
