/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda.gui;

/**
 *
 * @author delcenjo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFormularioContacto = new javax.swing.JPanel();
        PanelFormulario = new javax.swing.JPanel();
        PanelListaContactos = new javax.swing.JScrollPane();
        ListaContactos = new javax.swing.JList<>();
        iconoPersona = new javax.swing.JLabel();
        BarraEstado = new javax.swing.JPanel();
        MenuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFormularioContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelFormularioContacto.add(PanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 150));

        ListaContactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PanelListaContactos.setViewportView(ListaContactos);

        PanelFormularioContacto.add(PanelListaContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 190));

        iconoPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoPersona.png"))); // NOI18N
        PanelFormularioContacto.add(iconoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 20, 10));

        getContentPane().add(PanelFormularioContacto, java.awt.BorderLayout.CENTER);
        getContentPane().add(BarraEstado, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");
        MenuPrincipal.add(jMenu1);

        jMenu2.setText("Edit");
        MenuPrincipal.add(jMenu2);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraEstado;
    private javax.swing.JList<String> ListaContactos;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JPanel PanelFormularioContacto;
    private javax.swing.JScrollPane PanelListaContactos;
    private javax.swing.JLabel iconoPersona;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
